---
- name: Fail on Jessie
  assert:
    fail_msg: "Debian 8/Jessie are not supported"
    that:
      - ansible_distribution_major_version|int > 8
  when:
    - ansible_os_family == 'Debian'

# - name: Get MariaDB version
#   command: "mysql -V"
#   changed_when: false
#   register: _mariadb_version

# - name: Check that MariaDB is installed
#   assert:
#     fail_msg: This role only works with MariaDB
#     that:
#       - "'MariaDB' in _mariadb_version.stdout"
