---
- name: Fail on Jessie
  assert:
    fail_msg: "Debian 8/Jessie and Debian9/stretch are not supported"
    that:
      - ansible_distribution_major_version|int > 9
  when:
    - ansible_os_family == 'Debian'
