---
- import_tasks: assert.yml

- name: Set vars for OS family
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}.yml"
      skip: true

- import_tasks: user.yml

- include_tasks: configure.yml
  when:
    - mariadb_backup_directory|length > 0

- name: Install MariaDB-backup
  package:
    name: "{{ mariadb_backup_package }}"
